apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default-workload-cluster-configuration
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: default-workload-cluster-configuration-placement
        requeueAfterSeconds: 30
  template:
    metadata:
      name: default-workload-cluster-configuration-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        namespace: default-workload-cluster-config
        server: "{{server}}"
      project: default
      sources:
        - path: workload-cluster-config/overlays/{{name}}
          repoURL: https://github.com/troy-adianto/ocp-ztp-gitops.git
          targetRevision: main
          repositoryType: git
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: default-workload-cluster-configuration-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - workload
