apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-cluster-policies
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: workload-cluster-policies-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: workload-cluster-policies-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        namespace: workload-cluster-policies
        server: "{{server}}"
      project: default
      sources:
        - path: workload-cluster-policies
          repoURL: https://github.com/troy-adianto/ocp-ztp-gitops.git
          targetRevision: main
          repositoryType: git
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true

---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: workload-cluster-policies-placement
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - local-cluster
  clusterSets:
    - default
