apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-cluster-policies
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/troy-adianto/ocp-ztp-gitops.git
        revision: main
        files:
          - path: workload-cluster-policies/*.yaml
  template:
    metadata:
      name: 'policy-{{ .path.filenameNormalized }}'
      labels:
        app.kubernetes.io/part-of: workload-cluster-policies
    spec:
      project: default
      source:
        repoURL: https://github.com/troy-adianto/ocp-ztp-gitops.git
        targetRevision: main
        path: workload-cluster-policies
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
